dist: xenial
sudo: true
language: python
python:
    - "3.6"
addons:
-  apt:
-    packages:
      - ffmpeg
      - build-dep
      - graphviz
      - libgfortran3
      - libblas-dev
      - liblapack-dev
      - gfortran      
      - ocl-icd-opencl-dev
      - libopencl
      - cuda-gdb-src
      - cuda 
      - libgeos-dev
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - PYTHONUNBUFFERED=True
    - SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=disk

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq gcc-6 g++-6
  - pip install -r requirements_conda.txt
  - pip install -r requirements.txt
  - pip install -q http://download.pytorch.org/whl/cu91/torch-0.4.0-cp36-cp36m-linux_x86_64.whl
  - pip install torchvision  
before_script:
  - python setup.py build_ext --inplace
script:
  - python setup.py unittests
