environment:

  global:
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"

  matrix:

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%\\python -m pip install --upgrade pip"
  - "%PYTHON%\\Scripts\\pip install pymyinstall"
  - "%PYTHON%\\Scripts\\pymy_install3 --set=pyquickhelper"
  - "%PYTHON%\\Scripts\\pymy_install3 numba scikit-image scikit-learn statsmodels pillow"
  - "%PYTHON%\\Scripts\\pymy_install3 torch"
  - "%PYTHON%\\Scripts\\pip install torchvision"
  - "%PYTHON%\\Scripts\\pymy_install3 --task=tool --source=zip graphviz"
  - "%PYTHON%\\Scripts\\pip install pyquickhelper --no-deps"
  - "%PYTHON%\\Scripts\\pip install wcwidth backcall pyensae sphinx_bootstrap_theme"
  - "%PYTHON%\\Scripts\\pymy_install3 scikit-learn scipy cffi statsmodels cytoolz Pillow numba llvmlite"
  - "%PYTHON%\\Scripts\\pymy_install3 pycuda tensorflow"
  - "%PYTHON%\\Scripts\\pip install -r requirements_conda.txt"
  - "%PYTHON%\\Scripts\\pip install https://download.pytorch.org/whl/cpu/torch-1.0.1-cp37-cp37m-win_amd64.whl"
  - "%PYTHON%\\Scripts\\pip install -r requirements.txt"
  - "set PATH=%PATH%;C:\\projects\\ensae-teaching-dl\\build\\update_modules\\Graphviz\\bin"
  - set PYTHONPATH=src
build: off

test_script:
  - "%PYTHON%\\python -u setup.py unittests"

after_test:
  - "%PYTHON%\\python -u setup.py bdist_wheel"

artifacts:
  - path: dist
    name: ensae_teaching_dl
